(* autogenerated from github.com/mjschwenne/grackle/example *)
From Perennial.goose_lang Require Import prelude.
From Goose Require github_com.tchajed.marshal.

Section code.
Context `{ext_ty: ext_types}.

(* event.go *)

(* TimeStamp from timestamp.go *)

Definition TimeStamp := struct.decl [
  "hour" :: uint32T;
  "minute" :: uint32T;
  "second" :: uint32T
].

Definition Event := struct.decl [
  "id" :: uint32T;
  "name" :: stringT;
  "startTime" :: struct.t TimeStamp;
  "endTime" :: struct.t TimeStamp
].

Definition Event__approxSize: val :=
  rec: "Event__approxSize" "e" :=
    #0.

Definition MarshalTimeStamp: val :=
  rec: "MarshalTimeStamp" "t" "prefix" :=
    let: "enc" := ref_to (slice.T byteT) "prefix" in
    "enc" <-[slice.T byteT] (marshal.WriteInt32 (![slice.T byteT] "enc") (struct.get TimeStamp "hour" "t"));;
    "enc" <-[slice.T byteT] (marshal.WriteInt32 (![slice.T byteT] "enc") (struct.get TimeStamp "minute" "t"));;
    "enc" <-[slice.T byteT] (marshal.WriteInt32 (![slice.T byteT] "enc") (struct.get TimeStamp "second" "t"));;
    ![slice.T byteT] "enc".

Definition MarshalEvent: val :=
  rec: "MarshalEvent" "e" "prefix" :=
    let: "enc" := ref_to (slice.T byteT) "prefix" in
    "enc" <-[slice.T byteT] (marshal.WriteInt32 (![slice.T byteT] "enc") (struct.loadF Event "id" "e"));;
    let: "nameByte" := StringToBytes (struct.loadF Event "name" "e") in
    "enc" <-[slice.T byteT] (marshal.WriteInt (![slice.T byteT] "enc") (slice.len "nameByte"));;
    "enc" <-[slice.T byteT] (marshal.WriteBytes (![slice.T byteT] "enc") "nameByte");;
    "enc" <-[slice.T byteT] (MarshalTimeStamp (struct.loadF Event "startTime" "e") (![slice.T byteT] "enc"));;
    "enc" <-[slice.T byteT] (MarshalTimeStamp (struct.loadF Event "endTime" "e") (![slice.T byteT] "enc"));;
    ![slice.T byteT] "enc".

Definition UnmarshalTimeStamp: val :=
  rec: "UnmarshalTimeStamp" "s" :=
    let: "enc" := ref_to (slice.T byteT) "s" in
    let: "hour" := ref (zero_val uint32T) in
    let: "minute" := ref (zero_val uint32T) in
    let: "second" := ref (zero_val uint32T) in
    let: ("0_ret", "1_ret") := marshal.ReadInt32 (![slice.T byteT] "enc") in
    "hour" <-[uint32T] "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    let: ("0_ret", "1_ret") := marshal.ReadInt32 (![slice.T byteT] "enc") in
    "minute" <-[uint32T] "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    let: ("0_ret", "1_ret") := marshal.ReadInt32 (![slice.T byteT] "enc") in
    "second" <-[uint32T] "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    (struct.mk TimeStamp [
       "hour" ::= ![uint32T] "hour";
       "minute" ::= ![uint32T] "minute";
       "second" ::= ![uint32T] "second"
     ], ![slice.T byteT] "enc").

Definition UnmarshalEvent: val :=
  rec: "UnmarshalEvent" "s" :=
    let: "e" := struct.alloc Event (zero_val (struct.t Event)) in
    let: "enc" := ref_to (slice.T byteT) "s" in
    let: ("0_ret", "1_ret") := marshal.ReadInt32 (![slice.T byteT] "enc") in
    struct.storeF Event "id" "e" "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    let: "nameLen" := ref (zero_val uint64T) in
    let: "nameBytes" := ref (zero_val (slice.T byteT)) in
    let: ("0_ret", "1_ret") := marshal.ReadInt (![slice.T byteT] "enc") in
    "nameLen" <-[uint64T] "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    let: ("0_ret", "1_ret") := marshal.ReadBytesCopy (![slice.T byteT] "enc") (![uint64T] "nameLen") in
    "nameBytes" <-[slice.T byteT] "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    struct.storeF Event "name" "e" (StringFromBytes (![slice.T byteT] "nameBytes"));;
    let: ("0_ret", "1_ret") := UnmarshalTimeStamp (![slice.T byteT] "enc") in
    struct.storeF Event "startTime" "e" "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    let: ("0_ret", "1_ret") := UnmarshalTimeStamp (![slice.T byteT] "enc") in
    struct.storeF Event "endTime" "e" "0_ret";;
    "enc" <-[slice.T byteT] "1_ret";;
    ("e", ![slice.T byteT] "enc").

(* timestamp.go *)

End code.
